steps:
# 1) Build Docker image
- name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "--pull",
      "--no-cache",
      "-t",
      "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}",
      "."
    ]

# 2) Deploy na Cloud Run
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "run",
      "deploy",
      "${_SERVICE_NAME}",
      "--image",
      "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}",
      "--region",
      "${_DEPLOY_REGION}",
      "--platform",
      "${_PLATFORM}",
      "--allow-unauthenticated",
      "--quiet",
      "--traffic",
      "latest=100"
    ]

images:
- '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
