# cloudbuild.yaml — build + push + deploy (bez custom substitutions)
timeout: "1200s"

steps:
  # 0) Auth za Artifact Registry
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args: ['-c', 'gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet']

  # 1) Build image (Dockerfile u rootu)
  - name: gcr.io/cloud-builders/docker
    args: ['build','--pull','-t','europe-west1-docker.pkg.dev/$PROJECT_ID/matbot/matbot:$BUILD_ID','.']

  # 2) Push image
  - name: gcr.io/cloud-builders/docker
    args: ['push','europe-west1-docker.pkg.dev/$PROJECT_ID/matbot/matbot:$BUILD_ID']

  # 3) Deploy na Cloud Run i prebaci 100% saobraćaja
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [
      'run','deploy','matbot',
      '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/matbot/matbot:$BUILD_ID',
      '--region=europe-west1','--platform=managed',
      '--quiet','--set-traffic','latest=100'
    ]

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/matbot/matbot:$BUILD_ID'
