# cloudbuild.yaml — Build & Deploy (Dockerfile) -> Cloud Run

substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_PROJECT_ID: $PROJECT_ID
  _AR_REPOSITORY: matbot
  _SERVICE_NAME: matbot
  _DEPLOY_REGION: europe-west1
  _PLATFORM: managed

timeout: "1200s"

steps:
  # 0) Auth za Artifact Registry
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args: ['-c', 'gcloud auth configure-docker $_AR_HOSTNAME --quiet']

  # 1) Build image (Dockerfile u rootu)
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--pull', '-t', '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA', '.']

  # 2) Push image
  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA']

  # 3) Deploy na Cloud Run i preusmjeri 100% saobraćaja na latest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run','deploy','$_SERVICE_NAME',
        '--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA',
        '--region=$_DEPLOY_REGION',
        '--platform=$_PLATFORM',
        '--quiet',
        '--set-traffic','latest=100'
      ]

images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA'
