# cloudbuild.yaml — build+push+deploy (Dockerfile) sa tagom koji radi i lokalno
substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_PROJECT_ID: $PROJECT_ID
  _AR_REPOSITORY: matbot
  _SERVICE_NAME: matbot
  _DEPLOY_REGION: europe-west1
  _PLATFORM: managed
  _TAG: $BUILD_ID   # radi i za submit i za trigger; po želji možeš prepisati iz CLI-ja

timeout: "1200s"

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args: ['-c', 'gcloud auth configure-docker $_AR_HOSTNAME --quiet']

  - name: gcr.io/cloud-builders/docker
    args: ['build','--pull','-t','$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$_TAG','.']

  - name: gcr.io/cloud-builders/docker
    args: ['push','$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$_TAG']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [
      'run','deploy','$_SERVICE_NAME',
      '--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$_TAG',
      '--region=$_DEPLOY_REGION','--platform=$_PLATFORM',
      '--quiet','--set-traffic','latest=100'
    ]

images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$_TAG'
